services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  server:
    build:
      context: .
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  db:
    image: mariadb:10.11
    restart: always
    #user: root
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pma.rule=Host(`pma.localhost`)"
      - "traefik.http.routers.pma.entrypoints=web"
      - "traefik.http.services.pma.loadbalancer.server.port=80"
    networks:
      - web

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    expose:
      - "27017"
    networks:
      - web

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      mongo:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongoex.rule=Host(`mongo.localhost`)"
      - "traefik.http.routers.mongoex.entrypoints=web"
      - "traefik.http.services.mongoex.loadbalancer.server.port=8081"
    networks:
      - web

volumes:
  db-data:

networks:
  web:
    external: false
