services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

  app:
    image: ghcr.io/votre-repo-final:production
    container_name: ecoride-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.covoiturageecoride2.rule=Host(`ecoride-hauts-de-france.site`)"
      - "traefik.http.routers.covoiturageecoride2.entrypoints=web"
      - "traefik.http.services.covoiturageecoride2.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true