name: Test SSH with Password

on: [workflow_dispatch]

jobs:
  ssh-with-password:
    runs-on: ubuntu-latest
    steps:
      - name: 🔧 Installer sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: 🧪 Tester la connexion SSH avec mot de passe
        env:
          SSHPASS: ${{ secrets.GH_TOKEN }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} "echo ✅ Connexion SSH avec mot de passe réussie"
